name: StackMob
version: 2.2.0
author: antiPerson/BaconPied
main: uk.antiperson.stackmob.StackMob
website: https://www.spigotmc.org/resources/stackmob.29999/
softdepend: [MythicMobs,MiniaturePets,ProtocolLib]
description: The best entity stacking plugin.
load: STARTUP
commands:
    sm:
       description: The main command
permissions:
    stackmob.*:
      description: All administrator commands